Write-Output "This script has ZERO error checking enabled.  You must enter the protocol and URL excluding any of the virtual directotires such as OWA"
$url = Read-Host "Please enter the full URL to the exchange server.  such as https://mail.bank.com"
Start-Process "$($url)/OWA"
Start-Process "$($url)/ECP"
Start-Process "$($url)/EWS"
Start-Process "$($url)/Microsoft-Server-Activesync"
Start-Process "$($url)/OAB"
Start-Process "$($url)/RPC"
Start-Process "$($url)/MAPI"
Start-Process "$($url)/Powershell"